# Generated by Django 5.2.4 on 2025-07-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('visit_date', models.DateField()),
                ('visit_time', models.CharField(choices=[('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=6)),
                ('food_rating', models.PositiveSmallIntegerField()),
                ('cleanliness_rating', models.PositiveSmallIntegerField()),
                ('ambience_rating', models.PositiveSmallIntegerField()),
                ('service_rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('suggestions', models.TextField(blank=True, null=True)),
                ('recommendation', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
            ],
            options={
                'db_table': 'feedback',
                'managed': False,
            },
        ),
    ]
